// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFB4pBjLMBaa6NVBUXIccYck4N7IFDqro',
    appId: '1:1005237126754:web:dbb059c5ec5cf33aebb33b',
    messagingSenderId: '1005237126754',
    projectId: 'hmentregas-138ed',
    authDomain: 'hmentregas-138ed.firebaseapp.com',
    storageBucket: 'hmentregas-138ed.appspot.com',
    measurementId: 'G-TMSH4RYF8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJzf-varh7kaehDMGF5ZaBracBptSpkRM',
    appId: '1:1005237126754:android:6b79d420975c7da6ebb33b',
    messagingSenderId: '1005237126754',
    projectId: 'hmentregas-138ed',
    storageBucket: 'hmentregas-138ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDILOQ8AZETiwPKRvzHaAB8AeR2YeVu8k',
    appId: '1:1005237126754:ios:4dafad72bb5202b2ebb33b',
    messagingSenderId: '1005237126754',
    projectId: 'hmentregas-138ed',
    storageBucket: 'hmentregas-138ed.appspot.com',
    iosBundleId: 'com.example.hmEntregas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDILOQ8AZETiwPKRvzHaAB8AeR2YeVu8k',
    appId: '1:1005237126754:ios:5e5548444333c26bebb33b',
    messagingSenderId: '1005237126754',
    projectId: 'hmentregas-138ed',
    storageBucket: 'hmentregas-138ed.appspot.com',
    iosBundleId: 'com.example.hmEntregas.RunnerTests',
  );
}
